version: "3.7"
services:

  tests:
    image: test/node:10.14.2
    build: .
    user: "node"
    working_dir: /home/node/app
    volumes:
    - ./:/home/node/app
    command: "/bin/sh -c 'yarn && yarn test'"
